### ISSUE TITLE
Split into two repos?

### ISSUE THREAD

**Issue by jcs090218** [ObserverOfTime/tree-sitter-xml#5]
I'm trying to add XML support to the Emacs world, but I cannot since your repo isn't a standard tree-sitter-[language] kind of repository. I think it would be nice if you could split this into two repos so you have one language per repo. 🤔 

Thanks!

**Comment by amaanq** [comment]
typescript/tsx has the same style though

**Comment by jcs090218** [comment]
Ah, okay. I saw why it wasn't working.

It works now https://github.com/emacs-tree-sitter/tree-sitter-langs/pull/222! 🎉
