### ISSUE TITLE
Installation instructions missing

### ISSUE THREAD

**Issue by galou** [ObserverOfTime/tree-sitter-xml#6]
I'd like to try out this nice project but didn't manage to install it according to the [official doc](https://tree-sitter.github.io/tree-sitter/creating-parsers). The command `tree-sitter generate` needs to be run from the directories where `grammar.js` are but this is not obvious for new users. I didn't find out yet how to install the parser for example, even on the cited page.

**Comment by ObserverOfTime** [comment]
What is your use case?

**Comment by amaanq** [comment]
did you even bother to try `:TSInstall xml`

**Comment by galou** [comment]
Yes, there is no support for xml in `nvim-treesitter` as  in Tree-sitter itself.

**Comment by ObserverOfTime** [comment]
https://github.com/nvim-treesitter/nvim-treesitter/tree/master/queries/xml
